name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scikit-learn
  - statsmodels
  - tqdm
  - networkx
  - seaborn
  - hyperopt
  - nbgitpuller
